---

- name: Create kube directory
  command: "mkdir -p ~/.kube"

- name: kube directory permissions
  file:
    state: directory
    path: "~/.kube"
    mode: 0750

- name: doctl auth init
  command: "{{ role_path }}/doctl auth init -t {{ do_access_token }}"

# Download kubeconfig from DO
- name: Download kubeconfig
  command: "{{ role_path }}/doctl kubernetes cluster kubeconfig save {{ do_kubernetes_id }}"
